### PR TITLE
Add features for tunein Radio

### PR DESCRIPTION
**Pull request by vincentBesseau**

### CODE REVIEW

**Comment by Pierre-Gilles** [comment]
Hi! Thanks for this PR, it looks good but I don't manage to make it works.. I can't find the stationId and stationTitle ! How do you get this ?

I tried to call /music/currenttrack while playing a tuneInRadio to get the uri & title, but it's not working with theses infos... 

capture d ecran 2018-01-27 a 12 09 45

**Comment by vincentBesseau** [comment]
Salut Pierre-Gilles :-) !

stationId est retrouvable de cette manière :
https://help.tunein.com/customer/en/portal/articles/2232669-what-is-my-station-or-program-id-

stationTittle correspond au nom de la radio que tu auras sélectionné :-).

Pour info sur le forum j'ai le pseudo spenceur

Cordialement,

Besseau Vincent

Le 27 janv. 2018 12:10, "Pierre-Gilles" <notifications@github.com> a écrit :

Hi! Thanks for this PR, it looks good but I don't manage to make it works..
I can't find the stationId and stationTitle ! How do you get this ?

I tried to call /music/currenttrack while playing a tuneInRadio to get the
uri & title, but it's not working with theses infos...

[image: capture d ecran 2018-01-27 a 12 09 45]
<https://user-images.githubusercontent.com/7365207/35471418-0483b0f2-035b-11e8-9c5a-f5ea2034dadc.png>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/GladysProject/gladys-sonos/pull/2#issuecomment-360977693>,
or mute the thread

**Comment by Pierre-Gilles** [comment]
Hello!

Merci pour ta réponse rapide, j'ai donc tenté : 

```
gladys.modules.sonos.music.playTuneinRadio({deviceType: {device: 214}, stationId: 's2339', stationTitle: 'NRJ'})
.then(console.log)
.catch(console.log);
```

Sans succès, est-ce que j'ai fais quelques chose de mal ? ^^

**Comment by vincentBesseau** [comment]
Pas de soucis !
De mal non mais enlève juste le s devant l'id ^^

Fait donc plutôt cela :

var service = 'sonos'

gladys.modules.sonos.music.playTuneinRadio({deviceType: {device: 214}, stationId: 2339, stationTitle: 'NRJ’});

de mon côté je me suis fais un script dans Gladys : 

var service = 'sonos'

gladys.device.getByService({'service':service})
.then ((devices) => 
    gladys.deviceType.getByDevice(devices[0])
    .then((deviceType) => 
        gladys.modules.sonos.music.playTuneinRadio({'deviceType':deviceType[0], 'stationId':50776,'stationTitle':'NRJ'})
        .then(
            gladys.modules.sonos.music.setVolume({'deviceType':deviceType[0], 'volume':15})
        )
    )
)

**Comment by Pierre-Gilles** [comment]
Je confirme que ça marche parfaitement! :)

Merci pour ton aide, je merge ça tout de suite.

**Comment by Pierre-Gilles** [comment]
Sinon j'ai amélioré le README => https://github.com/GladysProject/gladys-sonos :)

**Comment by vincentBesseau** [comment]
Cool :) 
Merci a toi !

**Pull request merged**
